[project]
name = "llmops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed-Tamer-MT", email = "ntttmohamed@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "docx2txt==0.9",
    "faiss-cpu>=1.15.0",
    "fastapi==0.115.6",
    "ipykernel==6.30.0",
    "jinja2==3.1.4",
    "langchain==0.3.27",
    "langchain-community==0.3.27",
    "langchain-core==0.3.72",
    "langchain-google-genai==2.1.8",
    "langchain-groq==0.3.6",
    "langchain-openai==0.2.10",
    "langsmith>=0.11.1",
    "openai>=1.109.1",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "python-dotenv==1.1.1",
    "python-multipart==0.0.20",
    "structlog>=26.1.0",
    "uvicorn==0.32.1",
]

[project.scripts]
llmops = "llmops:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "ruff>=0.16.4",
]

[tool.basedpyright]
venvPath = "."
venv = ".venv"

